services:
  app:
    build: .
    container_name: taskflow_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      XDEBUG_MODE: coverage

  db:
    image: postgres:14
    container_name: taskflow_db
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
