services:
  app:
    build: .
    container_name: taskflow_app
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: coverage
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: taskflow_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:14
    container_name: taskflow_db
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
